[postgres.app]
drivername = "postgresql+psycopg2"
database = "healthetl"
username = "healthetl_user"
password = "healthetl_password"
host = "localhost"
port = 5433

[destination.postgres.credentials]
drivername = "postgresql+psycopg2"
database = "healthetl"
username = "healthetl_user"
password = "healthetl_password"
host = "localhost"
port = 5434
