name: "health_etl"
version: "1.0.0"
config-version: 2

profile: "health_etl"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  health_etl:
    staging:
      materialized: table
      +schema: staging
    data_warehouse:
      materialized: table
