name: "health_etl"
version: "1.0.0"
config-version: 2

profile: "health_etl"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  health_etl:
    +dbt-osmosis: "schema/{model}.yml"
    staging:
      materialized: incremental
      unique_key: ["user_activity_key"]
      on_schema_change: append_new_columns
      schema: staging
    dimensions:
      materialized: table
      schema: data_warehouse
      on_schema_change: append_new_columns
    facts:
      materialized: incremental
      unique_key: ["user_activity_key"]
      schema: data_warehouse
      on_schema_change: append_new_columns
