health_etl:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: "{{ env_var('user') }}"
      password: "{{ env_var('password') }}"
      port: 5434
      dbname: healthetl
      schema: healthetl_dbt
      threads: 3
      keepalives_idle: 0
      connect_timeout: 10
      retries: 3
