[project]
name = "health-etl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-duckdb>=1.9.3",
    "dlt[duckdb,postgres]>=1.11.0",
    "duckdb>=1.2.2",
    "psycopg2>=2.9.10",
]

[dependency-groups]
dev = []
