[project]
name = "health-etl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-duckdb>=1.9.3",
    "dbt-osmosis>=1.1.17",
    "duckdb>=1.2.2",
    "psycopg2>=2.9.10",
]
